name = "preview-ingress"
main = "src/index.ts"
compatibility_date = "2024-08-01"
routes = []

[[r2_buckets]]
binding = "PREVIEW_ARTIFACTS"
bucket_name = "preview-artifacts"
preview_bucket_name = "preview-artifacts"
